### ISSUE TITLE
How can i change language when running locally? (http://localhost:8080/synthesize/)

### ISSUE THREAD

**Issue by JohnClaw** [NeonGeckoCom/neon-tts-plugin-coqui#106]
### Objective

I tried making Neon tts to pronounce an Estonian sentence, but it pronounced this sentence with English voice. Is there an option to choose the language of Neon?

### Initial Implementation Requirements

an option of language switcher

**Comment by NeonBohdan** [comment]
Please ask [here](https://github.com/OpenVoiceOS/ovos-tts-server)
As we use this server

**Comment by Tomasinjo** [comment]
Add ?lang= to the request. For example:
http://192.168.10.15:8081/synthesize/zunaj-je-dvajset-stopinj?lang=sl-SI)

**Comment by NeonDaniel** [comment]
Closing as this appears to be resolved
