### ISSUE TITLE
Support dynamic model detection

### ISSUE THREAD

**Issue by NeonDaniel** [NeonGeckoCom/neon-tts-plugin-coqui#2]
Current implementation has hard-coded models for some languages; add support for loading other models if available and not specified in the plugin.

**Comment by NeonBohdan** [comment]
> Current implementation has hard-coded models for some languages; add support for loading other models if available and not specified in the plugin.

Clear. I will add ability to use any model from Coqui in any configuration 
And also any model properly uploaded to huggingface

**Comment by NeonBohdan** [comment]
This plugin has higher quality, faster and wider range of languages than coqui
So closing for now as of little use
