### ISSUE TITLE
Copying models to 🐸TTS

### ISSUE THREAD

**Issue by erogol** [NeonGeckoCom/neon-tts-plugin-coqui#73]
Hi all! Thanks for this great project. Models are also quite impressive. I wonder whether you would be open minded to copying your models to 🐸TTS models with the right attribution and license. If you say yes, I be on it.

**Comment by NeonDaniel** [comment]
Hello! Sorry for taking so long to get back to you here; lost this in my GitHub inbox.

All of our models are BSD-3 Licensed, so you are free to use any of our models as long as you keep that license notice. If you have docs or other places to provide credits or links, you can always link to this repository or our GitHub organization.

**Comment by erogol** [comment]
Just a heads up, we started adding the models to 🐸TTS. So feel free to provide feedback. 

-> https://github.com/coqui-ai/TTS/pull/2140

**Comment by NeonDaniel** [comment]
Looks like this is done with https://github.com/coqui-ai/TTS/pull/2140 merged
