### ISSUE TITLE
Support YourTTS Model

### ISSUE THREAD

**Issue by BWJ2310** [NeonGeckoCom/neon-tts-plugin-coqui#80]
Can you add the ability to support YourTTS model, say we have custom Style_wav input and Luanguage_name in the config? Also, I'm a little confused if this is a plugin for Coqui or MyCroft because the config looks like it's for MyCroft but the name is ...-plugin-coqui.

Thank you.

**Comment by NeonDaniel** [comment]
This is a Neon/OVOS/Mycroft-compatible TTS plugin to implement Coqui TTS models.

I'm not familiar with `YourTTS`, do you have a link to that project?

**Comment by BWJ2310** [comment]
this's the link to YourTTS, and it's an official model from Coqui. https://coqui.ai/blog/tts/yourtts-zero-shot-text-synthesis-low-resource-languages

**Comment by NeonDaniel** [comment]
This plugin is specific to Neon-trained models since we include some optimization for running on RPi that is not present in Coqui. Another plugin would be the best route to support other Coqui models
