### ISSUE TITLE
Torch Compatibility

### ISSUE THREAD

**Issue by NeonDaniel** [NeonGeckoCom/neon-tts-plugin-coqui#82]
Re #81 
Pickled models have specific dependencies; consider how to support torch and other dependency versions with the same distributed models

**Comment by NeonBohdan** [comment]
Some time ago we found that our pickled models don't work with `torch==1.13.0`
And we fixed it here https://github.com/NeonGeckoCom/neon-tts-plugin-coqui/blob/8c48260907710b64f0e141d136aa29492387fa77/requirements/requirements.txt#L3

But later hotfix `torch==1.13.1` was released 
And models work with it again 
Now even `torch==2.0.0` released, but I was unable to install in on RasPI

**Comment by NeonDaniel** [comment]
Ah, sounds like this was a one-off issue with that version; so our current dependency spec should work and there's nothing else  we need to do here
